[package]
name = "celect"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "benchmark"
path = "benchmark.rs"

[[bin]]
name = "breakdown"
path = "breakdown.rs"

[dependencies]
tree-sitter = "0.21"
colored = "2.1"
csv = "1.3"

[build-dependencies]
cc = "1.0"
